---
title: "Uzbekistan Health Reforms: Synthetic Control Model (Uzbekistan)"
author: Michelle Schultze
output: pdf_document
date: "2023-02-27"
---

```{r packages}
install.packages("readr", repos = "http://cran.us.r-project.org")
install.packages("microsynth", repos = "http://cran.us.r-project.org")
install.packages("LowRankQP", repos = "http://cran.us.r-project.org")
install.packages("tidyverse", repos = "http://cran.us.r-project.org")
library("readr")
library("tidyverse")
library("microsynth")
library("LowRankQP")
```

```{r dataset}
#setting intervention year
int_year = 2005

uzbek_data <- read_csv("/Users/michelle/uzbek-healthcare/data/uzbekistan_data_tidy.csv")
turk_data <- read_csv("/Users/michelle/uzbek-healthcare/data/turkistan_data_tidy.csv")
kyz_data <- read_csv("/Users/michelle/uzbek-healthcare/data/kyzylorda_data_tidy.csv")

uzbek_data <- uzbek_data %>% 
  mutate(Country = "UZ") %>%
  mutate(Intervention = if_else(year <= int_year, 0, 1))
turk_data <- turk_data %>%
  mutate(Country = "KZ", Intervention = 0) 
kyz_data <- kyz_data %>%
  mutate(Country = "KZ", Intervention = 0)

comparisons <- turk_data %>%
  merge(kyz_data, by = c("Region", "year", "births_count", "doctors_per_capita", "IMR_all", "LOS", "pc_beds", "pc_cancer", "pc_diabetes", "pc_digestive", "pc_genitourinary", "pc_injury", "pc_TB", "pop", "pop_m", "pop_f", "urban_percent", "hosp_count", "pc_hosp", "Country", "Intervention"), all = TRUE) %>%
  merge(uzbek_data, by = c("Region", "year", "births_count", "doctors_per_capita", "IMR_all", "LOS", "pc_beds", "pc_cancer", "pc_diabetes", "pc_digestive", "pc_genitourinary", "pc_injury", "pc_TB", "pop", "pop_m", "pop_f", "urban_percent", "hosp_count", "pc_hosp", "Country", "Intervention"), all = TRUE) %>%
  select(c("Region", "year", "births_count", "doctors_per_capita", "IMR_all", "LOS", "pc_beds", "pc_cancer", "pc_diabetes", "pc_digestive", "pc_genitourinary", "pc_injury", "pc_TB", "pop", "pop_m", "pop_f", "urban_percent", "hosp_count", "pc_hosp", "Country", "Intervention"))

```

```{r synthetic-control}
# ID will be "Region" column
# Time will be "year" column
# Intervention variable created above
# Intervention year set above
# Data starts 2002, ends 2018 (constricted by KZ data availability)

# Outcome vars will be c("doctors_per_capita", "IMR_all", "LOS", "pc_beds", "pc_cancer", "pc_diabetes", "pc_digestive", "pc_genitourinary", "pc_injury", "pc_TB", "pop", "hosp_count", "pc_hosp")
match.out.min <- c("doctors_per_capita", "IMR_all", "LOS", "pc_beds", 
                   "pc_cancer", "pc_diabetes", "pc_digestive", 
                   "pc_genitourinary", "pc_injury", "pc_TB", "pc_hosp")

# Because we're not matching exactly, we will use match.out.min/match.out.covar rather than match.out/match.covar

comparisons2 <- comparisons %>%
  select("Region", "year", "Intervention", "doctors_per_capita", "IMR_all", 
         "LOS", "pc_beds", "pc_cancer", "pc_diabetes", "pc_digestive", 
         "pc_genitourinary", "pc_injury", "pc_TB", "pop", "hosp_count", 
         "pc_hosp", "Country") %>%
  filter(year >= 2002, year <= 2018) %>%
  drop_na()

comparisons2['year'] = comparisons2['year'] - 2001

sea1 <- microsynth(comparisons2, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, check.feas=TRUE, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```


Matched just on the var of analysis:

```{r LOS}
match.out.min <- c("LOS")

sea1 <- microsynth(comparisons2, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```



```{r pc_hosp}
match.out.min <- c("pc_hosp")

sea1 <- microsynth(comparisons2, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```

```{r pc_digestive}
match.out.min <- c("pc_digestive")

sea1 <- microsynth(comparisons2, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```

```{r pc_genitourinary}
match.out.min <- c("pc_genitourinary")

sea1 <- microsynth(comparisons2, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```

```{r pc_TB}
match.out.min <- c("pc_TB")

sea1 <- microsynth(comparisons2, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```


```{r doctors_per_capita}
match.out.min <- c("doctors_per_capita")

sea1 <- microsynth(comparisons2, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```


```{r pop}
match.out.min <- c("pop")

sea1 <- microsynth(comparisons2, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```

```{r pc_diabetes}
match.out.min <- c("pc_diabetes")

sea1 <- microsynth(comparisons2, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```

```{r pc_injury}
match.out.min <- c("pc_injury")

sea1 <- microsynth(comparisons2, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```



KARAKALPAKSTAN ONLY

```{r}
# Outcome vars 
match.out.min <- c("doctors_per_capita", "IMR_all", "LOS", "pc_beds", 
                   "pc_cancer", "pc_diabetes", "pc_digestive", 
                   "pc_genitourinary", "pc_injury", "pc_TB", "pc_hosp")

#Make Karakalpakstan the only region of interest
comparisons3 <- comparisons2 %>%
  filter(Country != "UZ" | Region == "Karakalpakstan") %>%
  mutate(Intervention = case_when(Region == "Karakalpakstan" & year > 4 ~ 1,
                                  Region != "Karakalpakstan" | year <= 4 ~ 0))

sea1 <- microsynth(comparisons2, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, check.feas=TRUE, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```


Matched just on the var of analysis:

```{r LOS}
match.out.min <- c("LOS")

sea1 <- microsynth(comparisons3, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```



```{r pc_hosp}
match.out.min <- c("pc_hosp")

sea1 <- microsynth(comparisons3, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```

```{r pc_digestive}
match.out.min <- c("pc_digestive")

sea1 <- microsynth(comparisons3, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```

```{r pc_genitourinary}
match.out.min <- c("pc_genitourinary")

sea1 <- microsynth(comparisons3, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```

```{r pc_TB}
match.out.min <- c("pc_TB")

sea1 <- microsynth(comparisons3, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```


```{r doctors_per_capita}
match.out.min <- c("doctors_per_capita")

sea1 <- microsynth(comparisons3, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```


```{r pop}
match.out.min <- c("pop")

sea1 <- microsynth(comparisons3, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```

```{r pc_diabetes}
match.out.min <- c("pc_diabetes")

sea1 <- microsynth(comparisons3, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```

```{r pc_injury}
match.out.min <- c("pc_injury")

sea1 <- microsynth(comparisons3, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```

```{r pc_cancer}
match.out.min <- c("pc_cancer")

sea1 <- microsynth(comparisons3, idvar="Region", timevar="year", intvar="Intervention",
             start.pre=1, end.pre=4, end.post=17,
             match.out.min = match.out.min,
             match.covar = FALSE,
             result.var=match.out.min, omnibus.var=TRUE,
             test="lower", use.survey = FALSE, 
             perm=250, jack = 0, use.backup = TRUE,
             n.cores = min(parallel::detectCores(), 2))
summary(sea1)

plot_microsynth(sea1)
```
