---
title: "Uzbekistan Health Reforms: Tidying the Data (Turkistan region, Kazakhstan)"
author: Michelle Schultze
output: pdf_document
date: "2023-02-23"
---

```{r library-data, message=FALSE, warning=FALSE, include=FALSE}
library(readxl)
library(tidyverse)
library(broom)
library(tidymodels)
library(ggplot2)
library(pls)

doctors_per_capita <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                             sheet = "doctors-per-capita")
length_of_stay <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                             sheet = "LOS")
pop_all <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                      sheet = "pop")
pop_male <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                      sheet = "pop-male")
pop_female <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                      sheet = "pop-female")
births <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                         sheet = "live-births")
pc_beds <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                         sheet = "pc_beds")
hosp <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                         sheet = "hosp")
urban_percent <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                         sheet = "urban-percent")
IMR <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                         sheet = "IMR")
pc_cancer <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                         sheet = "pc_cancer")
pc_diabetes <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                         sheet = "pc_diabetes")
pc_TB <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                         sheet = "pc_TB")
pc_respiratory <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                         sheet = "pc_respiratory")
pc_injury <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                         sheet = "pc_injury")
pc_genitourinary <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                         sheet = "pc_genitourinary")
pc_digestive <- read_excel("/Users/michelle/uzbek-healthcare/data/turkistan_data.xlsx", 
                         sheet = "pc_digestive")
```

```{r tidying}
pc_TB <- pc_TB %>% 
  gather(key = year, value = pc_TB, -Region) 
pc_TB[["year"]] <- as.numeric(pc_TB$year)
pc_TB[["pc_TB"]] <- as.numeric(pc_TB$pc_TB)

# Extract vector for country-level
turk_pc_TB <- pc_TB %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
pc_TB <- pc_TB %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")


pc_beds <- pc_beds %>% 
  gather(key = year, value = pc_beds, -Region) 
pc_beds[["year"]] <- as.numeric(pc_beds$year)
pc_beds[["pc_beds"]] <- as.numeric(pc_beds$pc_beds)

# Extract vector for country-level
turk_pc_beds <- pc_beds %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
pc_beds <- pc_beds %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")


pc_cancer <- pc_cancer %>% 
  gather(key = year, value = pc_cancer, -Region) 
pc_cancer[["year"]] <- as.numeric(pc_cancer$year)
pc_cancer[["pc_cancer"]] <- as.numeric(pc_cancer$pc_cancer)

# Extract vector for country-level
turk_pc_cancer <- pc_cancer %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
pc_cancer <- pc_cancer %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")


pc_diabetes <- pc_diabetes %>% 
  gather(key = year, value = pc_diabetes, -Region) 
pc_diabetes[["year"]] <- as.numeric(pc_diabetes$year)
pc_diabetes[["pc_diabetes"]] <- as.numeric(pc_diabetes$pc_diabetes)

# Extract vector for country-level
turk_pc_diabetes <- pc_diabetes %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
pc_diabetes <- pc_diabetes %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")


pc_respiratory <- pc_respiratory %>% 
  gather(key = year, value = pc_respiratory, -Region) 
pc_respiratory[["year"]] <- as.numeric(pc_respiratory$year)
pc_respiratory[["pc_respiratory"]] <- as.numeric(pc_respiratory$pc_respiratory)

# Extract vector for country-level
turk_pc_respiratory <- pc_respiratory %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
pc_respiratory <- pc_respiratory %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")


pc_injury <- pc_injury %>% 
  gather(key = year, value = pc_injury, -Region) 
pc_injury[["year"]] <- as.numeric(pc_injury$year)
pc_injury[["pc_injury"]] <- as.numeric(pc_injury$pc_injury)

# Extract vector for country-level
turk_pc_injury <- pc_injury %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
pc_injury <- pc_injury %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")


pc_genitourinary <- pc_genitourinary %>% 
  gather(key = year, value = pc_genitourinary, -Region) 
pc_genitourinary[["year"]] <- as.numeric(pc_genitourinary$year)
pc_genitourinary[["pc_genitourinary"]] <- as.numeric(pc_genitourinary$pc_genitourinary)

# Extract vector for country-level
turk_pc_genitourinary <- pc_genitourinary %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
pc_genitourinary <- pc_genitourinary %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")


pc_digestive <- pc_digestive %>% 
  gather(key = year, value = pc_digestive, -Region) 
pc_digestive[["year"]] <- as.numeric(pc_digestive$year)
pc_digestive[["pc_digestive"]] <- as.numeric(pc_digestive$pc_digestive)

# Extract vector for country-level
turk_pc_digestive <- pc_digestive %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
pc_digestive <- pc_digestive %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")


length_of_stay <- length_of_stay %>% 
  gather(key = year, value = LOS, -Region) 
length_of_stay[["year"]] <- as.numeric(length_of_stay$year)
length_of_stay[["LOS"]] <- as.numeric(length_of_stay$LOS)

# Extract vector for country-level
turk_length_of_stay <- length_of_stay %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
length_of_stay <- length_of_stay %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")


pop_all <- pop_all %>% 
  gather(key = year, value = pop, -Region) 
pop_all[["year"]] <- as.numeric(pop_all$year)
pop_all[["pop"]] <- as.numeric(pop_all$pop)

# Extract vector for country-level
turk_pop_all <- pop_all %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
pop_all <- pop_all %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")


pop_male <- pop_male %>% 
  gather(key = year, value = pop_m, -Region) 
pop_male[["year"]] <- as.numeric(pop_male$year)
pop_male[["pop_m"]] <- as.numeric(pop_male$pop_m)

# Extract vector for country-level
turk_pop_male <- pop_male %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
pop_male <- pop_male %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")


pop_female <- pop_female %>% 
  gather(key = year, value = pop_f, -Region) 
pop_female[["year"]] <- as.numeric(pop_female$year)
pop_female[["pop_f"]] <- as.numeric(pop_female$pop_f)

# Extract vector for country-level
turk_pop_female <- pop_female %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
pop_female <- pop_female %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")


births <- births %>% 
  gather(key = year, value = births_count, -Region) 
births[["year"]] <- as.numeric(births$year)
births[["births_count"]] <- as.numeric(births$births_count)

# Extract vector for country-level
turk_births <- births %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
births <- births %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")


hosp <- hosp %>% 
  gather(key = year, value = hosp_count, -Region) 
hosp[["year"]] <- as.numeric(hosp$year)
hosp[["hosp_count"]] <- as.numeric(hosp$hosp_count)

# Extract vector for country-level
turk_hosp <- hosp %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
hosp <- hosp %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")



urban_percent <- urban_percent %>% 
  gather(key = year, value = urban_percent, -Region) 
urban_percent[["year"]] <- as.numeric(urban_percent$year)
urban_percent[["urban_percent"]] <- as.numeric(urban_percent$urban_percent)

# Extract vector for country-level
turk_urban_percent <- urban_percent %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
urban_percent <- urban_percent %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")


IMR <- IMR %>% 
  gather(key = year, value = IMR_all, -Region) 
IMR[["year"]] <- as.numeric(IMR$year)
IMR[["IMR_all"]] <- as.numeric(IMR$IMR_all)

# Extract vector for country-level
turk_IMR <- IMR %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
IMR <- IMR %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")


doctors_per_capita <- doctors_per_capita %>% 
  gather(key = year, value = doctors_per_capita, -Region) 
doctors_per_capita[["year"]] <- as.numeric(doctors_per_capita$year)
doctors_per_capita[["doctors_per_capita"]] <- as.numeric(doctors_per_capita$doctors_per_capita)

# Extract vector for country-level
turk_doctors_per_capita <- doctors_per_capita %>%
  filter(Region == "Turkistan region (formerly South Kazakhstan)")

# Remove country-level data for further analysis
doctors_per_capita <- doctors_per_capita %>%
  filter(Region != "Turkistan region (formerly South Kazakhstan)")
```



```{r}
turkistan_data <- births %>%
  merge(doctors_per_capita, by = c("Region", "year"), all = TRUE) %>%
  merge(hosp, by = c("Region", "year"), all = TRUE) %>%
  merge(IMR, by = c("Region", "year"), all = TRUE) %>%
  merge(length_of_stay, by = c("Region", "year"), all = TRUE) %>%
  merge(pc_beds, by = c("Region", "year"), all = TRUE) %>%
  merge(pc_cancer, by = c("Region", "year"), all = TRUE) %>%
  merge(pc_diabetes, by = c("Region", "year"), all = TRUE) %>%
  merge(pop_all, by = c("Region", "year"), all = TRUE) %>%
  merge(pop_male, by = c("Region", "year"), all = TRUE) %>%
  merge(pop_female, by = c("Region", "year"), all = TRUE) %>%
  merge(pc_digestive, by = c("Region", "year"), all = TRUE) %>%
  merge(pc_genitourinary, by = c("Region", "year"), all = TRUE) %>%
  merge(pc_injury, by = c("Region", "year"), all = TRUE) %>%
  merge(pc_respiratory, by = c("Region", "year"), all = TRUE) %>%
  merge(pc_TB, by = c("Region", "year"), all = TRUE) %>%
  merge(urban_percent, by = c("Region", "year"), all = TRUE) %>%
  filter(Region != "Arys city") %>%
  mutate(pc_hosp = (1000 * hosp_count / pop))


reg_turkistan_data <- turk_births %>%
  merge(turk_doctors_per_capita, by = c("Region", "year"), all = TRUE) %>%
  merge(turk_hosp, by = c("Region", "year"), all = TRUE) %>%
  merge(turk_IMR, by = c("Region", "year"), all = TRUE) %>%
  merge(turk_length_of_stay, by = c("Region", "year"), all = TRUE) %>%
  merge(turk_pc_beds, by = c("Region", "year"), all = TRUE) %>%
  merge(turk_pc_cancer, by = c("Region", "year"), all = TRUE) %>%
  merge(turk_pc_diabetes, by = c("Region", "year"), all = TRUE) %>%
  merge(turk_pop_all, by = c("Region", "year"), all = TRUE) %>%
  merge(turk_pop_male, by = c("Region", "year"), all = TRUE) %>%
  merge(turk_pop_female, by = c("Region", "year"), all = TRUE) %>%
  merge(turk_pc_digestive, by = c("Region", "year"), all = TRUE) %>%
  merge(turk_pc_genitourinary, by = c("Region", "year"), all = TRUE) %>%
  merge(turk_pc_injury, by = c("Region", "year"), all = TRUE) %>%
  merge(turk_pc_respiratory, by = c("Region", "year"), all = TRUE) %>%
  merge(turk_pc_TB, by = c("Region", "year"), all = TRUE) %>%
  merge(turk_urban_percent, by = c("Region", "year"), all = TRUE) %>%
  filter(Region != "Arys city") %>%
  mutate(pc_hosp = (1000 * hosp_count / pop))



## convert all per capitas to per 1k people, and make sure that prevalance/incidence matches with uzbekistan data

turkistan_data <- turkistan_data %>%
  mutate(doctors_per_capita = (1/10) * doctors_per_capita) %>% # doctors per 10k
  mutate(pc_cancer = (1/100) * pc_cancer) %>% # cancer per 100k (prevalence, matches)
  mutate(pc_diabetes = (1/100) * pc_diabetes) %>% # diabetes per 100k (incidence, matches, but kazakhstan is "diabetes mellitus")
  mutate(pc_TB = (1/100) * pc_TB) %>% # TB per 100k (incidence, matches) 
  mutate(pc_respiratory = (1/100) * pc_respiratory) %>% # resp per 100k (incidence, matches)
  mutate(pc_injury = (1/100) * pc_injury) %>% # injury per 100k (incidence, matches)
  mutate(pc_digestive = (1/100) * pc_digestive) %>% # digestive per 100k (incidence, matches)
  mutate(pc_genitourinary = (1/100) * pc_genitourinary) %>% # geni per 100k (incidence, matches)
  mutate(pc_beds = (1/10) * pc_beds) # beds per 10k

# calculated hosp by 1k
# infant mortality per 1k 


```




```{r export}
write.csv(turkistan_data, "/Users/michelle/uzbek-healthcare/data//turkistan_data_tidy.csv", row.names=FALSE)

write.csv(reg_turkistan_data, "/Users/michelle/uzbek-healthcare/data//regional_turkistan_data_tidy.csv", row.names=FALSE)

```

